/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Comment: typeof import('./src/components/Comment.vue')['default']
    CommentList: typeof import('./src/components/CommentList.vue')['default']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Message: typeof import('./src/components/Message.vue')['default']
    PersonalWindow: typeof import('./src/components/PersonalWindow.vue')['default']
    PostItem: typeof import('./src/components/PostItem.vue')['default']
    PostList: typeof import('./src/components/PostList.vue')['default']
    Reply: typeof import('./src/components/Reply.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Search.vue')['default']
    SeccondaryComment: typeof import('./src/components/SeccondaryComment.vue')['default']
    SecondaryComment: typeof import('./src/components/SecondaryComment.vue')['default']
    SortModeMenu: typeof import('./src/components/SortModeMenu.vue')['default']
    UserItem: typeof import('./src/components/UserItem.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
